### PR TITLE
Spacepod patch

### PR DESCRIPTION
**Pull request by MadSnailDisease**
Adds Switch Seats verb for Spacepod and Enter Pod now does nothing while inside the Pod.
spacepod.dm now sanitizes values for occupants after changing seats (the person who coded this originally forgot to do this)
Very sorry if there are any merge problems, the only content changes are in spacepod.dm, everything else is just whitespace changes =P
Also, dont use that click.dm nonsense, its outdated, lemme change that real quick

### CODE REVIEW

**Comment by MadSnailDisease** [comment]
grrrrrrrrr

**Comment by verboselucidity** [comment]
Uhh.... Not sure what happened with paradise.dme. It's showing a shitload of additions/deletions and that file is what is causing the merge conflict.

**Comment by MadSnailDisease** [comment]
I have no idea whats wrong with this branch, I am gonna restart and copypasta only the correct code into spacepod.dm in a new branch

**Comment by verboselucidity** [comment]
Closing due to errors within pull request. Instructed Snail on how to fix, new pull request should be submitted soon.

**Pull request closed without merging**
